name: wedding_app
description: "Wedding Invite Dashboard - Flutter Android App"
publish_to: 'none'

version: 1.0.5+5

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.2.5
  
  # Local notifications
  flutter_local_notifications: ^18.0.1
  
  # UI & Utilities
  google_fonts: ^6.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  fl_chart: ^0.71.0
  shared_preferences: ^2.5.5
  share_plus: ^12.0.2
  package_info_plus: ^9.0.1
  ota_update: ^7.1.0
  permission_handler: ^12.0.1
  flutter_background_service: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
